// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/rede/hgrunt.mdl
models/rede/leech.mdl
models/rede/roy.mdl
models/rede/v_357.mdl
models/rede/v_9mmar.mdl
models/rede/v_9mmhandgun.mdl
models/rede/v_crossbow.mdl
models/rede/v_egon.mdl
models/rede/v_gauss.mdl
models/rede/v_grenade.mdl
models/rede/v_m16a2.mdl
models/rede/v_medkit.mdl
models/rede/v_rpg.mdl
models/rede/v_satchel.mdl
models/rede/v_satchel_radio.mdl
models/rede/v_shotgun.mdl
models/rede/v_squeak.mdl
models/rede/v_tripmine.mdl
models/rede/w_battery.mdl
rede.wad
sound/rede/redamb/_comma.ogg
sound/rede/redamb/atmospherics_on.ogg
sound/rede/redamb/automedic_on.ogg
sound/rede/redamb/bell.ogg
sound/rede/redamb/bird2.ogg
sound/rede/redamb/bird6.ogg
sound/rede/redamb/communications_on.ogg
sound/rede/redamb/HEV6_logon.ogg
sound/rede/redamb/vitalsigns_on.ogg
sound/rede/redbarn/coastclear.ogg
sound/rede/redbarn/moths.ogg
sound/rede/redbarn/newsuit.ogg
sound/rede/redbarn/onleft.ogg
sound/rede/redbarn/onright.ogg
sound/rede/redbarn/setcord.ogg
sound/rede/redbarn/suitup.ogg
sound/rede/redbarn/thefly.ogg
sound/rede/redbarn/typein.ogg
sound/rede/redbarn/waitfinger.ogg
sound/rede/rede_materials.txt
sound/rede/redgman/rgman01.ogg
sound/rede/redgman/rgman02.ogg
sound/rede/redgman/rgman03.ogg
sound/rede/redgman/rgman04.ogg
sound/rede/redgman/rgman05.ogg
sound/rede/redgman/rgman06.ogg
sound/rede/redgman/rgman07.ogg
sound/rede/redgman/rgman08.ogg
sound/rede/redgman/rgman08b.ogg
sound/rede/redgman/rgman09.ogg
sound/rede/redgman/rgman10.ogg
sound/rede/redgman/rgman11.ogg
sound/rede/redgman/rgman13.ogg
sound/rede/redgman/rgman14.ogg
sound/rede/redgman/rgman15.ogg
sound/rede/redgman/rgman16.ogg
sound/rede/redgman/rgman17.ogg
sound/rede/redgman/rgman18.ogg
sound/rede/roy/aimforthehead.ogg
sound/rede/roy/americanpd.ogg
sound/rede/roy/areyoumad.ogg
sound/rede/roy/asfarasigo.ogg
sound/rede/roy/becarefull.ogg
sound/rede/roy/beenshot.ogg
sound/rede/roy/betterchance.ogg
sound/rede/roy/bojoke1.ogg
sound/rede/roy/bojoke2.ogg
sound/rede/roy/bojoke3.ogg
sound/rede/roy/buyashot.ogg
sound/rede/roy/canmakeit.ogg
sound/rede/roy/cannotfigure.ogg
sound/rede/roy/capitalistpig.ogg
sound/rede/roy/carefullwiththat.ogg
sound/rede/roy/comrade.ogg
sound/rede/roy/coveryou.ogg
sound/rede/roy/cutitout.ogg
sound/rede/roy/damnfool.ogg
sound/rede/roy/didyounotaskme.ogg
sound/rede/roy/didyouseethatthing.ogg
sound/rede/roy/diebastard.ogg
sound/rede/roy/dieddownhere.ogg
sound/rede/roy/doitlater.ogg
sound/rede/roy/donotbebetting.ogg
sound/rede/roy/dontbelievethat.ogg
sound/rede/roy/donttrypatience.ogg
sound/rede/roy/endoftheline.ogg
sound/rede/roy/fairwell.ogg
sound/rede/roy/gethellout.ogg
sound/rede/roy/gettingcloser.ogg
sound/rede/roy/goonahead.ogg
sound/rede/roy/gordon.ogg
sound/rede/roy/gordon2.ogg
sound/rede/roy/gotanother.ogg
sound/rede/roy/gotone.ogg
sound/rede/roy/hellogordon.ogg
sound/rede/roy/hellosir.ogg
sound/rede/roy/helpothers.ogg
sound/rede/roy/heygordon.ogg
sound/rede/roy/howmanydead.ogg
sound/rede/roy/hsguy.ogg
sound/rede/roy/icanttell.ogg
sound/rede/roy/idonotknow.ogg
sound/rede/roy/ihavebadfeeling.ogg
sound/rede/roy/ihavenoidea.ogg
sound/rede/roy/illstayhere.ogg
sound/rede/roy/illwait.ogg
sound/rede/roy/imonduty.ogg
sound/rede/roy/imsogood.ogg
sound/rede/roy/inbadshape.ogg
sound/rede/roy/ireckon.ogg
sound/rede/roy/iregretthis.ogg
sound/rede/roy/isgood.ogg
sound/rede/roy/isnotright.ogg
sound/rede/roy/ithinkihear.ogg
sound/rede/roy/keeplookout.ogg
sound/rede/roy/letsgo.ogg
sound/rede/roy/letsmoveit.ogg
sound/rede/roy/loose.ogg
sound/rede/roy/lotofdistance.ogg
sound/rede/roy/makeyourmove.ogg
sound/rede/roy/naturaly.ogg
sound/rede/roy/notachance.ogg
sound/rede/roy/nothowiseethings.ogg
sound/rede/roy/notright.ogg
sound/rede/roy/notscared.ogg
sound/rede/roy/notthinkingso.ogg
sound/rede/roy/notverycertain.ogg
sound/rede/roy/nyes.ogg
sound/rede/roy/nyett.ogg
sound/rede/roy/nyettcannot.ogg
sound/rede/roy/ofcourse.ogg
sound/rede/roy/oneless.ogg
sound/rede/roy/openfiregordon.ogg
sound/rede/roy/painfull.ogg
sound/rede/roy/perhaps.ogg
sound/rede/roy/pissmeoff.ogg
sound/rede/roy/protectus.ogg
sound/rede/roy/pssst.ogg
sound/rede/roy/responsibleformess.ogg
sound/rede/roy/ro_attack1.ogg
sound/rede/roy/ro_attack2.ogg
sound/rede/roy/ro_die1.ogg
sound/rede/roy/ro_die2.ogg
sound/rede/roy/ro_die3.ogg
sound/rede/roy/ro_pain1.ogg
sound/rede/roy/ro_pain2.ogg
sound/rede/roy/ro_pain3.ogg
sound/rede/roy/seeingyou.ogg
sound/rede/roy/seesomethingmove.ogg
sound/rede/roy/shutup.ogg
sound/rede/roy/sidearm.ogg
sound/rede/roy/somethingstinks.ogg
sound/rede/roy/soundsgood.ogg
sound/rede/roy/soundsgoodtome.ogg
sound/rede/roy/standguard.ogg
sound/rede/roy/standwellback.ogg
sound/rede/roy/staypost.ogg
sound/rede/roy/stophere.ogg
sound/rede/roy/stopthat.ogg
sound/rede/roy/stuffed.ogg
sound/rede/roy/takeserious.ogg
sound/rede/roy/takesomuch.ogg
sound/rede/roy/theadmin.ogg
sound/rede/roy/thinkingthesame.ogg
sound/rede/roy/toilet.ogg
sound/rede/roy/tombstone.ogg
sound/rede/roy/tooclose.ogg
sound/rede/roy/trophyroom.ogg
sound/rede/roy/uhoh.ogg
sound/rede/roy/vodka.ogg
sound/rede/roy/watchpoint.ogg
sound/rede/roy/welldone.ogg
sound/rede/roy/whatareyoutrying.ogg
sound/rede/roy/whatastench.ogg
sound/rede/roy/whatdotoyou.ogg
sound/rede/roy/whatinthename.ogg
sound/rede/roy/whatisgoingon.ogg
sound/rede/roy/winthiswar.ogg
sound/rede/roy/wishihadacold.ogg
sound/rede/roy/worsethanthis.ogg
sound/rede/roy/youeverseen.ogg
sound/rede/roy/youhavemyword.ogg
sound/rede/roy/youneedhelp.ogg
sound/rede/roy/youtalktomuch.ogg
sound/rede/roy/youwillregret.ogg
sprites/gst/extra.spr
sprites/gst/spritefont1.spr
